ANALISE ESTENOSE: Investigando Indice CxC

```{r Analise inicial}
df = df_backup
df$estenose = ifelse(df$estenose == "sim", 1, 0)

fd = data.frame(var_indice = numeric(0),
                tn = numeric(0), fp = numeric(0), 
                fn = numeric(0), tp = numeric(0))

pontos_de_corte = unique(sort(df$indice_CxC))

for (i in pontos_de_corte){
  df$controle = ifelse(df$indice_CxC > i, 1, 0) #
  
  #MEDIDAS DE DESEMPENHO
  #tb = table(df$controle, df$estenose) #tabela contigencia
  #print(tb)
  tn = nrow(df %>% filter(controle == 0 & estenose == 0)) #tb[1]
  fp = nrow(df %>% filter(controle == 1 & estenose == 0)) #tb[2]
  fn = nrow(df %>% filter(controle == 0 & estenose == 1)) #tb[3]
  tp = nrow(df %>% filter(controle == 1 & estenose == 1)) #tb[4]
  
  fd[nrow(fd)+1,] = c(i, tn, fp, fn, tp)
}

fd <- fd[-nrow(fd), ]
fd[is.na(fd)] <- 0

fd
fd$acuracia = (fd$tp + fd$tn) / (fd$tn + fd$fp + fd$fn + fd$tp)
fd$precisao = fd$tp / (fd$tp + fd$fp)

fd$sensibilidade = fd$tp / (fd$tp + fd$fn) # Recall
fd$especificidade = fd$tn / (fd$tn + fd$fp)

fd[is.na(fd)] <- 0
fd$f1 = 2 * (fd$precisao * fd$sensibilidade) / (fd$precisao + fd$sensibilidade)

fd$valor_pre_posi = fd$tp / (fd$tp + fd$fp)
fd$valor_pre_neg = fd$tn / (fd$tn + fd$fn)

# Métricas adicionais
fd$taxa_falsos_positivos = 1 - fd$especificidade # Taxa de Falsos Positivos (False Positive Rate)
fd$taxa_falsos_negativos = 1 - fd$sensibilidade # Taxa de Falsos Negativos (False Negative Rate)
fd$fdr = fd$fp / (fd$tp + fd$fp) # Taxa de Falsas Descobertas (False Discovery Rate)
fd$fo_r = fd$fn / (fd$tn + fd$fn) # Taxa de Falsas Omissões (False Omission Rate)
fd$indice_youden = fd$sensibilidade + fd$especificidade - 1 # Índice de Youden (Youden's Index)

# Coeficiente de Matthews (Matthews Correlation Coefficient)
fd$coef_matthews = (fd$tp*fd$tn - fd$fp*fd$fn) / sqrt((fd$tp+fd$fp)*(fd$tp+fd$fn)*(fd$tn+fd$fp)*(fd$tn+fd$fn))

# Definindo beta como 1 para F1-Score
beta <- 1
fd$fb_score = (1 + beta^2) * (fd$valor_pre_posi * fd$sensibilidade) / 
              ((beta^2 * fd$valor_pre_posi) + fd$sensibilidade)

fd[is.na(fd)] <- 0
fd_backup = fd
fd
round(fd, 2) %>% write_clip(dec = ",", col.names = TRUE) %>% print()

```


```{r GRAFICO CURVA ROC (Package)}
library(pROC)
model <- glm(estenose ~ indice_CxC, data=df, family="binomial")
predicted_probabilities <- predict(model, type="response")
predicted_probabilities = ifelse(predicted_probabilities >= 0.5, 1, 0)

roc_curve <- roc(df$estenose, predicted_probabilities)
plot(roc_curve, main="Curva ROC")
auc(roc_curve)
interva = ci(roc_curve)
ic1 = round(interva[1], 2)
ic = round(interva[2], 2)
ic2 = round(interva[3], 2)

area_curva = paste0(ic, " (IC:", ic1, " - ", ic2, ")")
area_curva

ggplot(df, aes(x=as.factor(x=estenose), y=indice_CxC, fill=as.factor(estenose))) + 
    geom_boxplot(show.legend = FALSE) + 
    geom_jitter(alpha=0.5, show.legend = FALSE, size=2, position=position_jitter(0.25), color="#141514") +
    geom_errorbar(stat = "summary", fun.data = "mean_se", width= 0.3, color="white") + 
    geom_point(stat = "summary", fun = "mean", show.legend = FALSE, color="red", size=2) + 
    theme(plot.title=element_text(face='italic'), axis.title=element_text(size=9, face='italic'),
          legend.position = "bottom") + 
    theme_minimal() + 
    theme(axis.line = element_line(colour = "black"),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.border = element_blank(),
          panel.background = element_blank())
```


```{r GRAFICO CURVA ROC (manual)}
##################  AREA SOBRE A CURVA - CALCULO MANUAL
fdd <- fd[order(fd$taxa_falsos_positivos),]
auc <- 0
for (i in 1:(nrow(fdd) - 1)) {
    delta_x <- fdd$taxa_falsos_positivos[i+1] - fdd$taxa_falsos_positivos[i]
    avg_y <- (fdd$sensibilidade[i+1] + fdd$sensibilidade[i]) / 2
    auc <- auc + delta_x * avg_y
}
auc

################## GRAFICO CURVA ROC
fd_grafico = fd[,c('sensibilidade','taxa_falsos_positivos')]
#fd_grafico %>% capture()
fd_grafico[c(4,7,16),]$taxa_falsos_positivos = fd_grafico[c(4,7,16),]$taxa_falsos_positivos - 0.02
fd_grafico[c(8, 17),]$taxa_falsos_positivos = fd_grafico[c(8, 17),]$taxa_falsos_positivos - 0.04
fd_grafico[c(18),]$taxa_falsos_positivos = fd_grafico[c(18),]$taxa_falsos_positivos + 0.04
fd_grafico[c(19),]$taxa_falsos_positivos = fd_grafico[c(19),]$taxa_falsos_positivos + 0.02
fd_grafico = rbind(fd_grafico, 1)

ggplot(fd_grafico, aes(x= taxa_falsos_positivos, y= sensibilidade)) +
  theme_bw() + 
  geom_step(color= "red", size=0.7) +
  #geom_line(color = "red", size=1) + 
  #geom_point(color= "black", alpha=0.5, size=3.5) +
  labs(title="Curve Roc: Index CxC", x="1 - Specificity", y="Sensibility",
       subtitle = paste("AUC =", area_curva)) +
  geom_abline(intercept = 0, slope = 1, linetype = "dashed", size=0.7) +
  scale_x_continuous(breaks=seq(from = 0, to = 1, by = 0.2), limits = c(0,1)) +
  scale_y_continuous(breaks=seq(from = 0, to = 1, by = 0.2), limits = c(0,1))

#ggsave("Curva_Roc.png", height=10, width=15, units="cm", dpi= 600)

```


```{r GRAFICO METRICAS DE AVALIAÇÃO}
################# GRAFICO 2D DAS MEDIDAS
fd_melt <- reshape2::melt(fd, id.vars="var_indice", 
                          measure.vars=c("acuracia", "sensibilidade", "especificidade", 
                                         "valor_pre_posi", 
                                         "valor_pre_neg", "f1", "taxa_falsos_positivos", "taxa_falsos_negativos", 
                                         "fdr", "fo_r", "indice_youden", "coef_matthews"))

# Plotando todas as métricas no mesmo gráfico
ggplot(fd_melt, aes(x=var_indice, y=value, color=variable)) +
  geom_line(size=1) +
  geom_point(alpha=0.5, size=3.5) +
  labs(title="Metrics vs Cutoff", 
       x="Index CxC (>)", y="Proportion", fill="") +
  scale_color_manual(values=c("#011627", "#3a86ff", "#DF5474", "#8ac926", "#F6BD60", "#BDA0BC", "#bde0fe",
                             "#8338ec", "#ffc2d1", "#a98467", "#f72585", "#eec170"), name="",
                     labels = c("Accuracy", "Sensibility", "Specificity", 
                                "Positive Predictive Value", "Negative Predictive Value",
                                "F1 Score", "False Positive Rate", "False Negative Rate", "False Discovery Rate",
                                "False Omission Rate", "Youden's Index", "Matthews Correlation Coefficient")) +
  theme_bw() + theme(legend.position="bottom") +
  scale_x_continuous(breaks=seq(from = 2, to = 10, by = 0.5), limits = c(2, 10))

#ggsave("Metrics.png", height=10, width=15, units="cm", dpi= 600)

##############################################

# Plotando apenas as métricas de sensibilidade, especificidade e acurácia no mesmo gráfico
ggplot(fd_melt[fd_melt$variable %in% c("sensibilidade", "especificidade", "acuracia"), ], 
       aes(x=var_indice, y=value, color=variable)) +
  geom_line(size=1) +
  geom_point(alpha=0.5, size=3.5) +
  labs(title="Metrics vs Cutoff", 
       x="Index CxC (>)", y="Proportion", fill="") +
  scale_color_manual(values=c("#3a86ff", "#DF5474", "#8ac926"), name="",
                     labels = c("Accuracy", "Sensibility", "Specificity")
                     ) +
  theme_bw() + theme(legend.position="bottom") +
  scale_x_continuous(breaks=seq(from = 2, to = 10, by = 0.5), limits = c(2, 10))

#ggsave("Metrics2.png", height=10, width=15, units="cm", dpi= 600)
```


```{r ANALISE ESTENOSE: Investigando Indice CxC ***MEDIDA DE TAMANHO DO EFEITO: Odds Ratio***}
fd$odds = NA
fd$p_value = NA

countt = 1
for (i in fd$var_indice){
  df$controle = ifelse(df$indice_CxC > i, 1, 0) #
  
  #MEDIDAS DE TAMANHO DE EFEITO
  modelo = glm(df$estenose ~ df$controle, data=df, family="binomial")
  modelo = modelo %>% analise_mod_antiga()
  fd$odds[countt] = modelo$OR_IC[1]
  fd$p_value[countt] = modelo$pvalor[1]
  countt = countt + 1
}
fd[,c('var_indice','odds','p_value')] %>% capture()
```


```{r Investigando Indice CxC ***IC estimado pela DISTRIBUIÇÃO BINOMIAL***}
fd = fd_backup

IC_function = function(medida, intervalos){
  ic_0 = as.character(rround(intervalos[1], 2))
  ic_1 = as.character(rround(intervalos[2], 2))
  medida = as.character(rround(medida, 2))
  texto = paste0(medida,' (',ic_0,' - ',ic_1,')')
  return(texto)
}

for (i in 1:nrow(fd)){
  # Acuracia
  teste_acuracia = binom.test(fd$tp[i] + fd$tn[i], fd$tn[i] + fd$fp[i] + fd$fn[i] + fd$tp[i], conf.level = 0.95)$conf.int
  fd$acuracia[i] = IC_function(as.numeric(fd$acuracia[i]), teste_acuracia)
  
  # Sensibilidade
  teste_sens = binom.test(fd$tp[i], fd$tp[i] + fd$fn[i], conf.level = 0.95)$conf.int
  fd$sensibilidade[i] = IC_function(as.numeric(fd$sensibilidade[i]), teste_sens)
  
  # Precisão (Valor Preditivo Positivo - VPP)
  teste_prec = binom.test(fd$tp[i], fd$tp[i] + fd$fp[i], conf.level = 0.95)$conf.int
  fd$precisao[i] = IC_function(as.numeric(fd$precisao[i]), teste_prec)
  
  # Valor Preditivo Negativo (VPN)
  teste_vpn = binom.test(fd$tn[i], fd$tn[i] + fd$fn[i], conf.level = 0.95)$conf.int
  fd$valor_pre_neg[i] = IC_function(as.numeric(fd$valor_pre_neg[i]), teste_vpn)
  
  # Especificidade
  teste_espec = binom.test(fd$tn[i], fd$tn[i] + fd$fp[i], conf.level = 0.95)$conf.int
  fd$especificidade[i] = IC_function(as.numeric(fd$especificidade[i]), teste_espec)
  
  # Taxa de Falsos Positivos (TFP) - FP / (FP + TN)
  teste_tfp = binom.test(fd$fp[i], fd$fp[i] + fd$tn[i], conf.level = 0.95)$conf.int
  fd$taxa_falsos_positivos[i] = IC_function(as.numeric(fd$taxa_falsos_positivos[i]), teste_tfp)
  
  # Taxa de Falsos Negativos (TFN) - FN / (TP + FN)
  teste_tfn = binom.test(fd$fn[i], fd$fn[i] + fd$tp[i], conf.level = 0.95)$conf.int
  fd$taxa_falsos_negativos[i] = IC_function(as.numeric(fd$taxa_falsos_negativos[i]), teste_tfn)
  
  # Taxa de Falsas Descobertas (FDR) - FP / (TP + FP)
  teste_fdr = binom.test(fd$fp[i], fd$tp[i] + fd$fp[i], conf.level = 0.95)$conf.int
  fd$fdr[i] = IC_function(as.numeric(fd$fdr[i]), teste_fdr)
  
  # Taxa de Falsas Omissões (FOR) - FN / (TN + FN)
  teste_for = binom.test(fd$fn[i], fd$tn[i] + fd$fn[i], conf.level = 0.95)$conf.int
  fd$fo_r[i] = IC_function(as.numeric(fd$fo_r[i]), teste_for)
  
  # Valor Preditivo Positivo (VPP) - TP / (TP + FP)
  teste_vpp = binom.test(fd$tp[i], fd$tp[i] + fd$fp[i], conf.level = 0.95)$conf.int
  fd$valor_pre_posi[i] = IC_function(as.numeric(fd$valor_pre_posi[i]), teste_vpp)

}

fd <- lapply(fd, function(x) if(is.numeric(x)) round(x, 2) else x)
fd <- as.data.frame(fd)
fd %>% capture()

#resetando
fd = fd_backup
```


```{r Investigando Indice CxC ***IC estimado pela DISTRIBUIÇÃO Z***}
fd = fd_backup

IC_function = function(x, n){
  medida_x = x/n
  Z <- qnorm(0.975) # Valor Z para IC de 95%
  SE <- sqrt((medida_x * (1 - medida_x)) / n)

  ic_0 <- medida_x - Z * SE
  ic_1 <- medida_x + Z * SE

  if (ic_0 < 0) {ic_0 = 0}
  if (ic_1 > 1) {ic_1 = 1}
  
  ic_0 = as.character(rround(ic_0, 2))
  ic_1 = as.character(rround(ic_1, 2))

  medida = as.character(rround(medida_x, 2))
  texto = paste0(medida,' (',ic_0,' - ',ic_1,')')
  return(texto)
}

IC_function(12, 16)

for (i in 1:nrow(fd)){
  # Acuracia
  fd$acuracia[i] = IC_function(fd$tp[i] + fd$tn[i], fd$tn[i] + fd$fp[i] + fd$fn[i] + fd$tp[i])
  
  # Sensibilidade
  fd$sensibilidade[i] = IC_function(fd$tp[i], fd$tp[i] + fd$fn[i])
  
  # Precisão (Valor Preditivo Positivo - VPP)
  fd$precisao[i] = IC_function(fd$tp[i], fd$tp[i] + fd$fp[i])
  
  # Valor Preditivo Negativo (VPN)
  fd$valor_pre_neg[i] = IC_function(fd$tn[i], fd$tn[i] + fd$fn[i])
  
  # Especificidade
  fd$especificidade[i] = IC_function(fd$tn[i], fd$tn[i] + fd$fp[i])
  
  # Taxa de Falsos Positivos (TFP) - FP / (FP + TN)
  fd$taxa_falsos_positivos[i] = IC_function(fd$fp[i], fd$fp[i] + fd$tn[i])
  
  # Taxa de Falsos Negativos (TFN) - FN / (TP + FN)
  fd$taxa_falsos_negativos[i] = IC_function(fd$fn[i], fd$fn[i] + fd$tp[i])
  
  # Taxa de Falsas Descobertas (FDR) - FP / (TP + FP)
  fd$fdr[i] = IC_function(fd$fp[i], fd$tp[i] + fd$fp[i])
  
  # Taxa de Falsas Omissões (FOR) - FN / (TN + FN)
  fd$fo_r[i] = IC_function(fd$fn[i], fd$tn[i] + fd$fn[i])
  
  # Valor Preditivo Positivo (VPP) - TP / (TP + FP)
  fd$valor_pre_posi[i] = IC_function(fd$tp[i], fd$tp[i] + fd$fp[i])

}

fd <- lapply(fd, function(x) if(is.numeric(x)) round(x, 2) else x)
fd <- as.data.frame(fd)
fd %>% capture()

fd_ic = fd

#resetando
fd = fd_backup

######################################
#CRIANDO GRAFICO 
fd_melt = data.frame(var_indice = numeric(0), 
                     variable = numeric(0), 
                     value = numeric(0),
                     minimo = numeric(0), 
                     maximo = numeric(0))

for (i in 1:nrow(fd_ic)){
  corte = fd_ic$var_indice[i]
  medida = substr(fd_ic$acuracia[i], 1,4)
  ic_0 = substr(fd_ic$acuracia[i], 7,10)
  ic_1 = substr(fd_ic$acuracia[i], 14,17)
  fd_melt[nrow(fd_melt)+1,] = c(corte, 'acuracia', medida, ic_0, ic_1)
}
for (i in 1:nrow(fd_ic)){
  corte = fd_ic$var_indice[i]
  medida = substr(fd_ic$sensibilidade[i], 1,4)
  ic_0 = substr(fd_ic$sensibilidade[i], 7,10)
  ic_1 = substr(fd_ic$sensibilidade[i], 14,17)
  fd_melt[nrow(fd_melt)+1,] = c(corte, 'sensibilidade', medida, ic_0, ic_1)
}
for (i in 1:nrow(fd_ic)){
  corte = fd_ic$var_indice[i]
  medida = substr(fd_ic$especificidade[i], 1,4)
  ic_0 = substr(fd_ic$especificidade[i], 7,10)
  ic_1 = substr(fd_ic$especificidade[i], 14,17)
  fd_melt[nrow(fd_melt)+1,] = c(corte, 'especificidade', medida, ic_0, ic_1)
}
fd_melt

fd_melt$var_indice = as.numeric(fd_melt$var_indice)
fd_melt$value = as.numeric(fd_melt$value)
fd_melt$minimo = as.numeric(fd_melt$minimo)
fd_melt$maximo = as.numeric(fd_melt$maximo)

ggplot(fd_melt, aes(x=var_indice, y=value, color=variable)) +
  geom_line(size=1) +
  geom_point(alpha=0.5, size=3.5) +
  labs(title="Metrics vs Cutoff", 
       x="Index CxC (>)", y="Proportion", fill="") +
  scale_color_manual(values=c("#3a86ff", "#DF5474", "#8ac926"), name="",
                     labels = c("Accuracy", "Sensibility", "Specificity")
                     ) +
  theme_bw() + theme(legend.position="bottom") + geom_errorbar(aes(ymin = minimo, ymax  = maximo)) + 
  scale_x_continuous(breaks=seq(from = 2, to = 10, by = 0.5), limits = c(2, 10))

#ggsave("Metrics3.png", height=10, width=15, units="cm", dpi= 600)

```